#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE=".env.local"   # gitignored; never committed

banner "Workie — hosted on Vercel + Turso"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Turso — create the database"
say "Workie's pipeline keeps running locally against workie.db. Turso is a hosted"
say "copy that Vercel can read, refreshed by 'npm run push:remote'."
note "Your corpus is ~7,800 postings / ~60MB — comfortably inside Turso's free tier."
open_url "https://turso.tech"
step "Sign up or log in (GitHub sign-in is the quickest)."
step "Create a database. Any name works — 'workie' is a fine choice."
step "Pick a location near you; it only affects read latency."
pause "Press Enter once the database exists."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Turso — connection URL and auth token"
say "Two values. Both live on the database's page in the Turso dashboard."
step "Find the connection URL. It starts with libsql:// — NOT the https:// one."
ask TURSO_DATABASE_URL "Paste the libsql:// URL:"
if [[ -n "${TURSO_DATABASE_URL:-}" && "$TURSO_DATABASE_URL" != libsql://* ]]; then
  warn "that doesn't start with libsql:// — if the site offered https://, look for the libsql form."
  confirm "Use it anyway?" || { say "Re-run the wizard when you have the libsql:// URL."; exit 1; }
fi
step "Now create an auth token for that database (often 'Create Token' / 'Tokens')."
say "Input is hidden — nothing is echoed to the screen."
ask_secret TURSO_AUTH_TOKEN "Paste the auth token:"
write_env TURSO_DATABASE_URL "$TURSO_DATABASE_URL"
write_env TURSO_AUTH_TOKEN "$TURSO_AUTH_TOKEN"
note "Written to .env.local, which is gitignored — it will never be committed."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Push the corpus up"
say "This applies the migrations to the empty database, then mirrors every posting."
note "Idempotent: it upserts rather than replaces, so re-running is always safe."
say ""
if npm run push:remote; then
  printf '  %s✓%s corpus pushed\n' "$GREEN" "$RESET"
else
  warn "push failed — the URL or token is probably wrong."
  note "Fix them in .env.local and re-run: npm run push:remote"
  confirm "Continue to the Vercel steps anyway?" || exit 1
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vercel — import the repo into your PERSONAL account"
say "Workie is a personal project. It belongs on your own Vercel account, not on a team."
warn "This is the step that goes wrong. Read the scope line before clicking Import."
say ""
step "Log in as dongyeop0810@gmail.com — not a work address."
open_url "https://vercel.com/new"
step "Look at the SCOPE selector at the top of the import screen."
say "    Vercel preselects whichever scope you used last, so if you have ever"
say "    deployed anything for work, that team is what is selected right now."
say "    It must read your personal account before you continue."
say ""
say "Your repo is PRIVATE, so Vercel needs GitHub access to it — and that access is"
say "per scope. Authorizing the GitHub app for a team does not authorize it for your"
say "personal account, so expect to grant it again here even though you have before."
step "Import DY0810/Job_Dashboard."
step "If it isn't listed: 'Adjust GitHub App Permissions', then grant access to it."
say ""
warn "Vercel will REFUSE to deploy a commit whose author it does not recognize."
say "    A push only deploys if the commit author is an identity on the Vercel"
say "    account. This repo is set to commit as dongyeop0810@gmail.com for exactly"
say "    that reason — check it before you push, because a global git config set to"
say "    a work address silently reintroduces the block:"
say ""
say "        git config user.email        # want: dongyeop0810@gmail.com"
say ""
say "    Setting it is not enough on its own: a squash-merged PR is re-authored by"
say "    GitHub to the PUBLIC EMAIL of the account that opened the PR, which threw"
say "    the work address back onto main even with the local config correct. That is"
say "    why this repo pushes to main directly rather than through PRs."
say ""
say "    A deployment already blocked this way does not need a new commit — hit"
say "    Redeploy in the dashboard, which is authorized by you rather than by the"
say "    commit author."
say ""
step "Before deploying, open 'Environment Variables' and add BOTH of these:"
say ""
say "    TURSO_DATABASE_URL     $TURSO_DATABASE_URL"
say "    TURSO_AUTH_TOKEN       (copy it out of .env.local — see below)"
say ""
note "Set both for Production, Preview AND Development, or preview deploys break."
note "Without them the site builds fine but renders a 'not configured' state."
say ""
say "The token is shown once by Turso and cannot be read back, so copy it from the"
say "file rather than hunting for it in the dashboard:"
say ""
say "    grep '^TURSO_AUTH_TOKEN=' .env.local | cut -d= -f2- | tr -d '\\n' | pbcopy"
say ""
step "Deploy."
pause "Press Enter once the deployment finishes."
ask WORKIE_URL "Paste the deployment URL:"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Check it's actually serving postings"
if [[ -n "${WORKIE_URL:-}" ]]; then
  open_url "$WORKIE_URL"
  step "You should see the Engineering tab with real job titles."
  say ""
  say "If it says 'not configured', the env vars didn't save — add them in"
  say "Vercel → Settings → Environment Variables, then redeploy."
  say "If the tabs are empty but the page renders, stage 3's push didn't land."
  say ""
  say "If Vercel asks you to log in to see your own site, it landed on a team scope"
  say "rather than your personal account — team deployments are SSO-gated. A personal"
  say "Hobby project is public by default, which is what you want here."
  say ""
  note "From now on every 30-minute refresh pushes up automatically —"
  note "scripts/refresh.sh runs push:remote at the end of each cycle."
else
  warn "no URL captured — open the deployment from your Vercel dashboard."
fi

finish
